-record(session_parameter, {host, port, ip, senderCompId, targetCompId, heartbeatInterval, callbackModule}).
-record(fix_in_messages, {number, message}).
-record(fix_out_messages, {number, message}).
-record(last_startup_run, {key, time}).
